name: Deploy to env

on:
  pull_request:
    types: [closed]
    branches:
      - "production"
      - "staging"
      - "dev"
  workflow_dispatch:
    inputs:
      PROMOTION_ENV:
        description: "Select an environment to deploy the app"
        required: true
        type: choice
        default: dev
        options:
          - dev
          - production
          - staging

jobs:
  build:
    name: Promote
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: >-
      ( 
      ${{ github.ref == format('refs/heads/{0}', github.event.inputs.PROMOTION_ENV) }} 
      && 
      ${{ github.event.inputs.PROMOTION_ENV != 'production'}}
      ) 
      || 
      (
      ${{ github.ref == 'refs/heads/master' }} 
      && 
      ${{ github.event.inputs.PROMOTION_ENV == 'production'}}
      )
    environment: ${{ github.ref_slug }}
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      - name: Promote
        run: |
          echo Running on $(basename ${GITHUB_REF}) branch
          echo "With Environment ${{ job.environment }}"
          echo "Vars: ${{ vars.STORAGEACCOUNT }} "
