name: Deploy to env

on:
  pull_request:
    types:
      - closed
    branches:
      - "production"
      - "staging"
      - "dev"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Promote
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: Promote
        env:
          JOB_ENV: ${{ job.environment }}
          SLUG: ${{ github.ref_name }}
          VAR: ${{ toJSON(vars) }}

        run: |
          echo Running on $(basename ${GITHUB_REF}) branch
          echo "$JOB_ENV"
          echo "$SLUG"
          echo "$VAR"
    

  logcontext:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          
        run: echo "$GITHUB_CONTEXT"
        
        
